package si.fri.rso.stationcatalog.services;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import org.springframework.stereotype.Controller;
import org.springframework.stereotype.Service;
import si.fri.rso.stationcatalog.models.entities.Station;
import si.fri.rso.stationcatalog.models.repositories.StationRepository;

@Component
public class StationService {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private StationRepository stationRepository;


    public Station addStation(Station s){
        return stationRepository.save(s);
    }

    public Iterable<Station> getAllStations(){
        return stationRepository.findAll();
    }
}
